# Generated by Django 4.2 on 2026-01-12 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
