# Generated by Django 4.2 on 2026-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0003_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, default='concert_images/default.jpg', null=True, upload_to='concert_images/'),
        ),
    ]
