# Generated by Django 4.2 on 2026-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0005_remove_concert_image_alter_concert_available_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/'),
        ),
    ]
