# Generated by Django 4.2 on 2026-01-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0006_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
