# Generated by Django 4.2 on 2026-01-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0007_alter_concert_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
