# Generated by Django 4.2 on 2026-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0009_user_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(null=True, upload_to='concert_images/'),
        ),
    ]
