# Generated by Django 4.2 on 2026-01-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0010_alter_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/'),
        ),
    ]
