# Generated by Django 4.2 on 2026-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0012_alter_concert_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
