# Generated by Django 4.2 on 2026-01-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbooking_app', '0015_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
